-- Seed membership plans
insert into public.membership_plans (tier, name, price_monthly, price_yearly, features, max_listings, highlighted) values
  ('free', 'Free', 0, 0, '{"1 basic listing","Community access","Search visibility"}', 1, false),
  ('basic', 'Basic', 29, 290, '{"3 enhanced listings","Priority placement","Review responses","Badge display","Email support"}', 3, false),
  ('premium', 'Premium', 79, 790, '{"10 featured listings","Top search placement","Analytics dashboard","Photo gallery","Phone support","Social media links"}', 10, true),
  ('elite', 'Elite', 199, 1990, '{"Unlimited listings","Homepage featured","Blog posting","Event creation","Dedicated account manager","Custom branding","API access"}', 999, false);

-- Seed listings from JSON data
insert into public.listings (slug, name, type, description, city, state, species, success_rate, price_min, price_max, physical_intensity, rating, review_count, phone, website, image, featured) values
  ('rocky-mountain-elk-guides', 'Rocky Mountain Elk Guides', 'guide', 'Premier guided elk hunting in the Colorado Rockies. Our expert guides have over 20 years of experience navigating the backcountry for trophy bull elk. We offer 5-7 day pack-in trips with comfortable base camps, world-class glassing spots, and proven calling strategies.', 'Gunnison', 'Colorado', '{"Elk","Mule Deer"}', 85, 4500, 7500, 4, 4.8, 47, '(970) 555-0142', 'https://example.com/rm-elk', '/images/elk-hunt.jpg', true),
  ('summit-peak-outfitters', 'Summit Peak Outfitters', 'outfitter', 'Full-service mountain hunting outfitter in the heart of Montana big game country. We provide everything from lodging and meals to quality horses and experienced wranglers. Specializing in elk, mule deer, and mountain lion hunts across 50,000 acres of private and permitted public land.', 'Bozeman', 'Montana', '{"Elk","Mule Deer","Mountain Lion","Black Bear"}', 78, 5000, 12000, 3, 4.6, 62, '(406) 555-0198', 'https://example.com/summit-peak', '/images/mountain-outfitter.jpg', true),
  ('gulf-coast-deep-sea-charters', 'Gulf Coast Deep Sea Charters', 'charter', 'Experience world-class deep sea fishing in the Gulf of Mexico. Our fleet of custom 42-foot sportfishing boats are equipped with the latest electronics and tackle. From red snapper to blue marlin, our experienced captains put you on the fish.', 'Destin', 'Florida', '{"Red Snapper","Grouper","Mahi-Mahi","Tuna","Marlin"}', 92, 800, 2500, 2, 4.9, 128, '(850) 555-0167', 'https://example.com/gulf-coast', '/images/deep-sea.jpg', true),
  ('big-woods-whitetail-guides', 'Big Woods Whitetail Guides', 'guide', 'Dedicated whitetail deer hunting in the legendary big woods of Wisconsin and Michigan. We hunt mature bucks using a combination of stand hunting, still hunting, and strategic drives. Our properties are carefully managed with year-round food plots and trail camera networks.', 'Rhinelander', 'Wisconsin', '{"Whitetail Deer"}', 72, 2000, 4500, 2, 4.5, 35, '(715) 555-0123', 'https://example.com/big-woods', '/images/whitetail.jpg', false),
  ('pacific-northwest-salmon-charters', 'Pacific Northwest Salmon Charters', 'charter', 'Fish the legendary rivers and coastal waters of the Pacific Northwest for king salmon, silver salmon, and steelhead. Our guides know every hole, riffle, and tide change. We offer both river drift boat trips and ocean charter fishing.', 'Astoria', 'Oregon', '{"Salmon","Steelhead","Halibut"}', 88, 350, 600, 2, 4.7, 89, '(503) 555-0156', 'https://example.com/pnw-salmon', '/images/salmon-fishing.jpg', true),
  ('lone-star-hog-outfitters', 'Lone Star Hog Outfitters', 'outfitter', 'Texas-sized wild hog hunting adventures on over 10,000 acres of prime ranch land. We offer day hunts, overnight packages, and corporate group events. Hunt from blinds, spot-and-stalk, or use thermal optics for exciting night hunts.', 'San Angelo', 'Texas', '{"Wild Boar"}', 95, 300, 1500, 2, 4.4, 73, '(325) 555-0189', 'https://example.com/lone-star-hog', '/images/hog-hunt.jpg', true),
  ('thunder-ridge-turkey-guides', 'Thunder Ridge Turkey Guides', 'guide', 'Premier spring and fall turkey hunting in the Ozark Mountains of Missouri. Our guides are champion callers who know how to work a gobbler into range. Hunt from comfortable ground blinds or run-and-gun style on beautiful hardwood ridges.', 'West Plains', 'Missouri', '{"Turkey"}', 80, 800, 1800, 2, 4.6, 41, '(417) 555-0134', 'https://example.com/thunder-ridge', '/images/turkey-hunt.jpg', false),
  ('great-lakes-walleye-charters', 'Great Lakes Walleye Charters', 'charter', 'Top-rated walleye charter fishing on Lake Erie and Lake Huron. Our experienced captains consistently put clients on trophy walleye using the latest techniques and electronics. We provide all tackle, bait, and fish cleaning services.', 'Port Clinton', 'Ohio', '{"Walleye","Perch","Smallmouth Bass"}', 90, 400, 700, 1, 4.8, 95, '(419) 555-0145', 'https://example.com/great-lakes', '/images/walleye-fishing.jpg', false),
  ('northwoods-bear-outfitters', 'Northwoods Bear Outfitters', 'outfitter', 'Guided black bear hunting in the dense forests of northern Minnesota. We maintain over 60 active bait stations on thousands of acres of prime bear habitat. Our comfortable lodge accommodations and home-cooked meals make for an unforgettable hunting experience.', 'Grand Rapids', 'Minnesota', '{"Black Bear"}', 75, 2500, 4000, 2, 4.3, 28, '(218) 555-0178', 'https://example.com/northwoods-bear', '/images/bear-hunt.jpg', false),
  ('flyway-waterfowl-guides', 'Flyway Waterfowl Guides', 'guide', 'Experience incredible duck and goose hunting along the Mississippi Flyway in Arkansas. We hunt flooded timber, rice fields, and managed wetlands for mallards, pintails, gadwall, and snow geese. Our state-of-the-art blind setups and premium decoy spreads deliver consistent results.', 'Stuttgart', 'Arkansas', '{"Duck","Goose"}', 88, 500, 1200, 2, 4.7, 56, '(870) 555-0167', 'https://example.com/flyway-waterfowl', '/images/waterfowl-hunt.jpg', true),
  ('high-plains-antelope-outfitters', 'High Plains Antelope Outfitters', 'outfitter', 'Hunt pronghorn antelope on the wide-open plains of Wyoming. Our ranch properties hold excellent antelope populations with high buck-to-doe ratios. We offer both rifle and archery hunts with comfortable ranch house lodging and hearty western meals.', 'Casper', 'Wyoming', '{"Pronghorn Antelope"}', 90, 3000, 5000, 3, 4.5, 33, '(307) 555-0192', 'https://example.com/high-plains', '/images/antelope-hunt.jpg', false),
  ('striper-alley-charters', 'Striper Alley Charters', 'charter', 'Chase trophy striped bass in the legendary waters off Montauk, Long Island. Our experienced captains target stripers from May through November using live bait, trolling, and topwater techniques. Full-day and half-day trips available.', 'Montauk', 'New York', '{"Striped Bass","Bluefish"}', 82, 600, 1200, 2, 4.6, 67, '(631) 555-0143', 'https://example.com/striper-alley', '/images/striper-fishing.jpg', false),
  ('heartland-pheasant-outfitters', 'Heartland Pheasant Outfitters', 'outfitter', 'World-class pheasant hunting in the heart of South Dakota. Our managed habitat produces incredible bird numbers, and our trained pointing dogs ensure productive hunts. Enjoy comfortable lodge accommodations, excellent food, and traditional upland hunting at its finest.', 'Pierre', 'South Dakota', '{"Pheasant","Quail","Grouse"}', 85, 1500, 3500, 2, 4.7, 51, '(605) 555-0165', 'https://example.com/heartland-pheasant', '/images/pheasant-hunt.jpg', false),
  ('prairie-wind-upland-guides', 'Prairie Wind Upland Guides', 'guide', 'Experience the best upland bird hunting in Kansas with our expert guides and well-trained bird dogs. We hunt pheasant, quail, and prairie chicken across thousands of acres of CRP land and native grass prairie. Our half-day and full-day guided hunts are perfect for both seasoned hunters and newcomers.', 'Colby', 'Kansas', '{"Pheasant","Quail","Prairie Chicken"}', 78, 400, 900, 3, 4.4, 29, '(785) 555-0176', 'https://example.com/prairie-wind', '/images/upland-hunt.jpg', false),
  ('mountain-creek-fly-fishing', 'Mountain Creek Fly Fishing', 'charter', 'Guided fly fishing adventures on the pristine mountain streams and rivers of western North Carolina. Our guides are experts at matching the hatch and reading the water. We target wild brown trout, rainbow trout, and brook trout in some of the most beautiful settings in the East.', 'Bryson City', 'North Carolina', '{"Trout"}', 80, 300, 550, 2, 4.5, 44, '(828) 555-0188', 'https://example.com/mountain-creek', '/images/fly-fishing.jpg', false),
  ('bayou-country-adventures', 'Bayou Country Adventures', 'guide', 'Authentic Louisiana hunting experiences in the bayous and marshes of Cajun country. From world-class duck hunting in flooded rice fields to exciting alligator hunts in the swamp, we offer unique adventures you won''t find anywhere else. Enjoy genuine Cajun hospitality and cuisine.', 'Lafayette', 'Louisiana', '{"Duck","Goose","Wild Boar"}', 82, 600, 2000, 2, 4.6, 38, '(337) 555-0199', 'https://example.com/bayou-country', '/images/bayou-hunt.jpg', false);
